--- #YAML:1.0
name:                Date-Simple-Range
version:             1.0
abstract:            A range of Date::Simple objects
license:             GPLv2
author:              
    - Alessandro Zummo <a.zummo@towertech.it>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor:               0
    Date::Simple:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
